name: Build and Publish Flatpak

on:
  push:
    branches: [ main ]
    paths:
      - '**.json'
      - '**.sh'
      - '**.png'
      - '**.desktop'
  workflow_dispatch:

jobs:
  build-mekhq:
    name: Build MekHQ Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: mekhq.flatpak
          manifest-path: com.megamek.mekhq.json
          cache-key: flatpak-builder-${{ github.sha }}
          repository-url: https://flathub.org/repo/flathub.flatpakrepo
          xvfb: false
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mekhq-flatpak
          path: mekhq.flatpak
          retention-days: 5
